{% set version="1.0.1" %}
about:
    home: https://github.com/mehrdadbakhtiari/adVNTR
    license: BSD 3-Clause
    summary: A tool for genotyping Variable Number Tandem Repeats (VNTR) from sequence data
package:
    name: advntr
    version: {{ version }}
build:
  number: 0
  skip: false
  script: python setup.py install --single-version-externally-managed --record=record.txt
  entry_points:
    - advntr=advntr.__main__:main
source:
  fn: adVNTR_{{ version }}.tar.gz
  url: https://github.com/mehrdadbakhtiari/adVNTR/archive/{{ version }}.tar.gz
  sha256: ec973bbac42f74782b3c2b3f70d4dfdb2a2ac7b6ed356b15a8fec3736c3cb57f
requirements:
  build:
    - python
    - setuptools
    - cython
    - scipy
    - networkx==1.11
    - matplotlib
  run:
    - python
    - cython
    - scipy
    - networkx==1.11
    - joblib
    - biopython
    - blast
    - muscle
    - pysam>=0.9.1.4
    - htslib==1.3
